# CONTROLE DE AUDIO
bind = , F2, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , F3, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+

# TEMAS
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"
#exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
#env = QT_QPA_PLATFORMTHEME,qt6ct
##env = QT_STYLE_OVERRIDE,kvantum
#exec = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_STYLE_OVERRIDE,kvantum

# MONITORS
monitor=HDMI-A-1,1920x1080@100,0x0,1
monitor=eDP-1, 1920x1080@60,-1920x0,1

# EXEC-ONCE
exec-once = waybar

# gaps_in and out
    gaps_in = 10
    gaps_out = 20

    border_size = 4


# KEYBINDS
bind = $mainMod, R, exec, rofi -show drun
bind = $mainMod, T, exec, $terminal
bind = $mainMod, L, exec, hyprlock # Lock screen
bind = $mainMod SHIFT, T, exec, flatpak run io.missioncenter.MissionCenter # TASK MANAGER

# MOVIMENTAR A JANELA PARA OUTRO MONITOR
bind = $mainMod SHIFT, right, movewindow, mon:r
bind = $mainMod SHIFT, left, movewindow, mon:l

# MAXIMIZAR
bind = $mainMod, F, fullscreen, 1

# PRINTAR A TELA
bind = $mainMod, PRINT, exec, hyprshot -m region

export HYPRSHOT_DIR="$HOME/Pictures/"

